### ISSUE TITLE
"Getting started" documentation

### ISSUE THREAD

**Issue by tskluzac** [xtracthub/xtract-sampler#13]
Can we add some basic instructions as to how to run this for the following tasks (in the README). We don't need to spend too much time on this, but given the complexity of this extractor, it's likely a good idea to do this sooner than later. 

- [x] How to run the new two-phase automated training. 
- [x] Locations where the intermediate and final model files are stored. 
- [ ] How to run predictions on files.

**Comment by rewong03** [comment]
Done
